INSERT ALL
  INTO Reviews_tb VALUES (6000, 'OK', 'OUR MEETING LASTED LONGER THAN EXPECTED, ENDED UP GETTING HUNGRY AND NO FOOD COULD BE PROVIDED') 
  INTO Reviews_tb VALUES (6001, 'GOOD', 'DEFINETLY WILL COME AGAIN') 
  INTO Reviews_tb VALUES (6002, 'POOR', 'NOT REALLY ACCESIBLE INCOMPLETE') 
  INTO Reviews_tb VALUES (6003, 'VERY GOOD', 'EVERYTHING WAS PERFECT HAS EVERYTHING NEEDED') 
  INTO Reviews_tb VALUES (6004, 'GOOD', 'HIGH QUALITY FOOD') 
  INTO Reviews_tb VALUES (6005, 'VERY POOR', 'ROOM WAS NOT READY WHEN WE ARRIVED, DIRTY TOILETS') 
  INTO Reviews_tb VALUES (6006, 'VERY GOOD', 'QUICK SHORT MEETING BRAND NEW EQUIPMENT') 
  INTO Reviews_tb VALUES (6007, 'POOR', 'WAS TOLD THERE WAS PARKING NEARBY BUT 25 MINS WALK') 
  INTO Reviews_tb VALUES (6008, 'VERY GOOD', 'HIGH QUALITY FOOD')
  INTO Reviews_tb VALUES (6009, 'GOOD', ' REALLY GOOD FOOD') 
  INTO Reviews_tb VALUES (6010, 'GOOD', ' VERY PROFESSIONAL EVERYTHING AS DESCRIBED')
SELECT * FROM DUAL;
COMMIT;
