CREATE TABLE Building_tb (
  BUILDING_ID NUMBER(4) NOT NULL constraint PK_BUILDING_ID primary key,
  BUILDING_NAME VARCHAR2(30) NOT NULL,
  BUILDING_ADDRESS VARCHAR2(255) NOT NULL,
  B_LAT NUMBER(10,6) NOT NULL,
  B_LONG NUMBER(10,6) NOT NULL,
  CONTACT_NUMBER NUMBER(25) NOT NULL,
  ROOMS NUMBER(3) NOT NULL,
  FLOORS NUMBER(3) NOT NULL,
  PARKING NUMBER(1) NOT NULL,
  CATERING NUMBER(1) NOT NULL,
  CATERING_ID NUMBER(4)
);