CREATE TABLE Room_tb (
  ROOM_ID NUMBER(4) constraint PK_ROOMS_ID primary key, 
  ROOM_NUMBER NUMBER(3) NOT NULL,
  FLOOR NUMBER(3) NOT NULL,
  CAPACITY NUMBER(3) NOT NULL,
  FACILITIES VARCHAR2(50) constraint RFACILITIES CHECK (FACILITIES in ('WHITEBOARD', 'PROJECTOR', 'SPEAKERS', 'VIDEO CONFERENCE')),
  ACCESSIBILITY NUMBER(1) NOT NULL,
  BUILDING_ID NUMBER(4) constraint FK_BUILDINGID REFERENCES Building_tb, 
  TOILET_ID NUMBER(4) constraint FK_TOILETID REFERENCES Toilet_tb
);

